### ISSUE TITLE
Feature Request - Add more Tld

### ISSUE THREAD

**Issue by TiiTcHY** [ail-project/ail-typo-website#3]
I have been doing a comparison of the data extracted from your platform and DNSTwist. Although your platform has a lot more domains returned there are some that DNSTwist pick up which you do not. This mainly falls under the WrongTLD Algorithm if i apply a .co.uk domain to DNSTwist it will give me back .com, .biz .net etc domains. However, your platform only strips out the .uk section to change the domain instead of stripping out the .co.uk.

Would it be possible to request such a feature?

**Comment by DavidCruciani** [comment]
Hi @TiiTcHY,

Thanks you for your report, and we work on it actually to change all algorithms that are affected by this.

By the way, changes will be done on the library, https://github.com/ail-project/ail-typo-squatting.

Nice catch, Thanks again.
I'll close this issue when the push will be done.

**Comment by DavidCruciani** [comment]
Hi @TiiTcHY,

The public instance is up to date now and running with some update. The TLD problem is normally fix.

Thanks again for the report you did and don't hesitate to give us a feedback or to report other issues.

**Comment by TiiTcHY** [comment]
Hi @DavidCruciani,

Thanks for the quick turn around with this. 

I have just updated the python module but now when trying to use the "runall" example on [https://github.com/ail-project/ail-typo-squatting] I am getting the following error?

`OSError: [WinError 87] The parameter is incorrect` on the first line for `from ail_typo_squatting import runAll`

**Comment by DavidCruciani** [comment]
Hi @TiiTcHY,

The issue was due to Faup library that need to be run under linux os, but I changed it to use [tldextract](https://github.com/john-kurkowski/tldextract) now.

You can check this commit https://github.com/ail-project/ail-typo-squatting/commit/43cefbf2666b42db6fc6a586ed92ea3ae3a142c3 to see changes.

In the future, if you have any question or report about the library please open [issue](https://github.com/ail-project/ail-typo-squatting/issues) on the other repo.

Hope you'll enjoy the code with those modifications.
